{{- if eq .Values.provider "aks" }}
apiVersion: crossplane.giantswarm.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: {{ .Values.clusterName }}-cert-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  clusterName: {{ .Values.clusterName }}
  provider: {{ .Values.provider }}
  location: {{ .Values.providers.azure.location }}
  resourceGroupName: {{ include "azure.resourceGroupName" . }}
  subject: system:serviceaccount:kube-system:cert-manager-app
  subscriptionID: {{ .Values.providers.azure.subscriptionId }}
  template: |
      giantSwarmClusterIssuer:
        acme:
          dns01:
            azureDNS:
              identityClientID: "${clientID}"

      cert-manager:
        extraObjects:
          - |
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: cert-manager-identity
              namespace: kube-system
              labels:
                {{- include "labels.common" . | nindent 16 }}
            data:
              clientID: "${clientID}"
              tenantID: "${tenantID}"
{{- end }}
