version: 2.1
orbs:
  architect: giantswarm/architect@5.12.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package-and-push-chart
        app_catalog: cluster-catalog
        app_catalog_test: cluster-test-catalog
        chart: cm-crossplane-resources
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
